
language: java
jdk: openjdk11
install: true
script: mvn install -Dmaven.javadoc.skip=true -B -V
after_success: 
  -mvn clean test jacoco:report coveralls:reportafter
  -bash <(curl -s https://coveralls.io/bash)
